#!/usr/bin/perl

# ebi ###
#   Make a section of an index of eboards

my $num = shift;
my $digits = $num;
if (($num =~ m/^[0-9]*$/) && ($num < 10)) {
  $digits = "0$num";
}

print <<"EBI";
  <tr>
    <td>Class $num</td>
    <td>&day$digits;</td>
    <td>&cal$digits;</td>
    <td><ulink url='eboard.$digits.html'>&title$digits;</ulink></td>
    <td><ulink url='eboard.$digits.md'>Source $num</ulink></td>
    <td><ulink url='eboard.$digits.html'>HTML $num</ulink></td>
  </tr>
EBI
