#!/usr/bin/perl
# out START FINISH
#   Make the specified outline

my $start = $ARGV[0];
my $finish = $ARGV[1];
if (!$finish) { $finish = $start; }

for ($num = $start; $num <= $finish; $num++) {
  $num = $num + 0;
  $shortnum = $num;
  if ($num < 10) { $num = "0$num"; }
  $fname = "outline.$num.md";
  if (! -f $fname) {
    open OUTLINE, ">", "outline.$num.md";
    print OUTLINE<<"CONTENTS";
---
title: Outline $shortnum
number: $shortnum
link: false
---
{% include outline.md %}
CONTENTS
  } # if
} # for
